Added TrainOptions class and fixed some comments
ucfai/knightros-gambit pull request #137
Opened 2022-02-03 01:02 UTC by fshcat

2022-02-03 01:24 UTC, nashirj commented
We discussed this and decided to wait for the checkpointing branch to be closed so that parameters related to model saving can be included in the TrainOptions class.

2022-02-03 16:07 UTC, ryPattillo reviewed
Looks like a good start, there are a bunch of more training parameters that we need to consider but that can be added on another pull request

2022-02-17 17:52 UTC, nashirj requested changes
This looks much cleaner, nice work and thanks for doing this.

Couple things in addition to my other comments, I tried running the code and got this stack trace:
```bash
Traceback (most recent call last):
  File "train.py", line 287, in <module>
    main()
  File "train.py", line 283, in main
    train_on_mcts(nnet, exploration=5, training_episodes=2, mcts_simulations=2, options=mcts_options)
  File "train.py", line 251, in train_on_mcts
    dataset = create_dataset(options.games, mcts_moves)
  File "train.py", line 131, in create_dataset
    game_data = [training_game(val_approximator, move_approximator) for _ in range(games)]
  File "train.py", line 131, in <listcomp>
    game_data = [training_game(val_approximator, move_approximator) for _ in range(games)]
  File "train.py", line 72, in training_game
    moves, move_probs, move = move_approximator(board)
  File "train.py", line 249, in <lambda>
    mcts_moves = lambda board: mcts.get_tree_results(mcts_simulations, nnet, board, temperature=5)
  File "/home/nashirj/Documents/school/UCF/clubs/knightros-gambit/chess-AI/mcts.py", line 57, in get_tree_results
    self.search(board, nnet)
TypeError: search() missing 1 required positional argument: 'device'
```

Also, prob not in the scope of this PR, but there was also a warning about creating a tensor from a list of arrays being slow:
```
train.py:136: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  /opt/conda/conda-bld/pytorch_1640811806235/work/torch/csrc/utils/tensor_new.cpp:201.)
  move_probs = torch.tensor([move_prob for game in game_data for move_prob in game[2]]).float()
```
prob not hard to fix that warning while you're doing other stuff if you don't mind.

2022-02-17 17:52 UTC, nashirj commented on chess-AI/train.py
> +        """
This entire block should be indented one level less, so that the start and end """ line up

2022-02-17 17:52 UTC, nashirj commented on chess-AI/train.py
> +        options: settings/hyperparameters for training
Can you pls specify that the type is TrainOptions so people know where to look to see all the available hyperparameters

2022-02-17 17:52 UTC, nashirj commented on chess-AI/train.py
> +    train_on_mcts(nnet, exploration=5, training_episodes=5, mcts_simulations=100, options=mcts_options)
Can you pls make variables for all the parameters specified in the function call? It'll make it easier for @ryPattillo and I to update this code to handle either the dashboard/reading from json. You can initialize the variables with the values here, and we can use those for reference as the default for the hyperparams.json file we'll make

2022-02-17 18:37 UTC, nashirj approved these changes

2022-02-17 18:39 UTC, merged